spring:
  application:
    name: books
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/assignment?currentSchema=public
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    show-sql: true
    generate-ddl: true
server:
  port: 9100
  servlet:
    context-path: /api